### PR TITLE
Export prepareWhere to Update placeholders in where condition as needed

### PR DESCRIPTION
**Pull request by rubanour**

### CODE REVIEW

**Comment by odino** [comment]
Is there any reason why one would want to prepare the query without executing it?

**Comment by rubanour** [comment]
@odino to run the query within a transaction

**Comment by odino** [comment]
Is it possible to apply this logic to any query, regardless? So that people dont have to prepare them manually within transactions. Also, `prepareWhere` is kind of misleading, since this can also be used in other queries (ie. `INSERT INTO table (x, y,z) VALUES(?)`)

**Comment by rubanour** [comment]
The point that we are using `connection.execute` directly in our code when we use transactions and that's why we needed to expose `prepareBulk` earlier and now we're exposing `prepareQuery` (renamed from prepareWhere).
There is a suggestion to add two functions `executeQuery(query, params, connection)` and `executeBulk(query, params, connection)` that take a specific connection to execute the query within instead of getting one from the pool. 
What do you think? @odino @joejean @geshan

**Comment by joejean** [comment]
@rubanour Ruba, If I understand well `executeQuery(query, params, connection)` will require us to manage connections outside of the library, right? If that's the case I don't think it is a good idea. 
I see them being useful only for transactions: like when we call `startTransaction()`

**Review by AyhamAlzoubi — APPROVED** [review]
Since the other solutions won't be nicer, I am fine with this approach

**Comment by joejean** [comment]
@rubanour This is available under version 1.0.8. Thanks

**Pull request merged**
