### PR TITLE
Support mysql 8

### PR DESCRIPTION
**Pull request by geshan**
Refer : https://github.com/sidorares/node-mysql2/issues/628

### CODE REVIEW

**Review by AyhamAlzoubi — APPROVED** [review]

**Comment by geshan** [comment]
@joejean how about merging it :)

**Comment by odino** [comment]
@joejean / @AyhamAlzoubi ping :)

**Comment by joejean** [comment]
Sorry for the delay @geshan. This is now published under 2.0.0. We made it a major release just to be on the safe side as we did not test it thoroughly.

**Comment by geshan** [comment]
Thanks.

**Pull request merged**
